import {
  applyLevelToState,
  campaignLevels,
  getCampaignLevel,
  VIEWPORT_HEIGHT,
  VIEWPORT_WIDTH,
} from "@/game/data/campaignLevels";
import { enemyHitboxTemplate } from "@/game/data/enemyCatalog";
import { resetEnemySeed } from "@/game/entities/createEnemy";
import type { GameMode, GameState } from "@/game/types/gameTypes";

const baseHints = [
  "Moverse: WASD o flechas",
  "Combo: J x3",
  "Especial: K",
  "Agarrar / lanzar: L, L otra vez",
  "Esquive: Shift",
  "Pausa: P",
];

export function createInitialGameState(mode: GameMode = "campaign"): GameState {
  resetEnemySeed();
  const firstLevel = getCampaignLevel(0);

  const state: GameState = {
    mode,
    phase: "title",
    currentLevelIndex: 0,
    totalLevels: campaignLevels.length,
    scene: {
      type: "carriage_intro",
      gateClosed: false,
      gateRightX: null,
      waveIndex: 0,
      waveTriggered: false,
      secondWaveTriggered: false,
      bossTriggered: false,
      victoryWalkTriggered: false,
      activeHazards: [],
    },
    player: {
      id: "ricky",
      name: "Ricky Ferreyra",
      x: firstLevel.layout.entryX,
      y: firstLevel.entryY,
      z: 0,
      vx: 0,
      vy: 0,
      vz: 0,
      width: 68,
      depth: 34,
      speed: 420,
      jumpStrength: 720,
      gravity: 1800,
      hp: 100,
      maxHp: 100,
      onGround: true,
      facing: "right",
      isMoving: false,
      actionState: "idle",
      attack: {
        activeMs: 0,
        cooldownMs: 0,
        damage: 22,
        range: 108,
        width: 88,
        currentAction: null,
        queuedAction: null,
        actionTimerMs: 0,
        actionRecoveryMs: 0,
        attackChainIndex: 0,
        attackWindowMs: 0,
        hitbox: {
          ...enemyHitboxTemplate,
          width: 88,
          height: 36,
          offsetX: 18,
          offsetY: 6,
        },
        struckEnemyIds: [],
      },
      queuedAction: null,
      actionTimerMs: 0,
      actionRecoveryMs: 0,
      grabTargetId: null,
      recoverableHp: 0,
      dashVectorX: 0,
      dashVectorY: 0,
      dashInvulnerableMs: 0,
      hurtCooldownMs: 0,
      speedBoostMs: 0,
      attackBoostMs: 0,
      shieldMs: 0,
      blindMs: 0,
      invertControlsMs: 0,
    },
    enemies: [],
    projectiles: [],
    items: [],
    camera: {
      x: 0,
      viewportWidth: VIEWPORT_WIDTH,
      viewportHeight: VIEWPORT_HEIGHT,
    },
    input: {
      left: false,
      right: false,
      up: false,
      down: false,
      jump: false,
      attack: false,
      special: false,
      grab: false,
      dash: false,
      pause: false,
    },
    levelBounds: firstLevel.bounds,
    levelLayout: firstLevel.layout,
    lastDtMs: 0,
    startedAtMs: null,
    updatedAtMs: null,
    survivalWave: 0,
    survivalWavesCleared: 0,
    survivalMinibossesCleared: 0,
    hud: {
      levelName: firstLevel.name,
      elapsedMs: 0,
      hints: baseHints,
      enemyCount: 0,
      objective: firstLevel.openingObjective,
      completionTitle: null,
      completionSummary: null,
      pickupMessage: null,
      activePickup: null,
      stationResult: null,
    },
    runStats: {
      score: 0,
      stationScoreStart: 0,
      stationStartElapsedMs: 0,
      comboCurrent: 0,
      comboBest: 0,
      comboTimerMs: 0,
      stationDamageTaken: 0,
      stationSpecialsUsed: 0,
      stationThrowsUsed: 0,
      stationGrabsUsed: 0,
      stationDashesUsed: 0,
      stationBasicAttacksUsed: 0,
      stationHazardHitsTaken: 0,
      stationHazardKills: 0,
      stationKills: 0,
    },
  };

  applyLevelToState(state, 0, false);
  if (mode === "survival") {
    state.hud.levelName = "Supervivencia";
    state.hud.objective = "Oleadas infinitas. Elegí cómo querés arrancar.";
  }
  return state;
}
